[package]
name = "rdb-driver-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
rdb-core = { path = "../core" }
async-trait = "0.1"
redis = { version = "1.3", features = ["tokio-comp", "tls-native-tls", "tokio-native-tls-comp"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
testcontainers = "0.27"
testcontainers-modules = { version = "0.15", features = ["redis"] }
