//! SQL keyword set for the editor lexer — Postgres/MySQL/SQLite.

pub const KEYWORDS: &[&str] = &[
    "SELECT",
    "FROM",
    "WHERE",
    "GROUP",
    "BY",
    "ORDER",
    "LIMIT",
    "OFFSET",
    "JOIN",
    "LEFT",
    "RIGHT",
    "INNER",
    "OUTER",
    "ON",
    "AS",
    "AND",
    "OR",
    "NOT",
    "IN",
    "IS",
    "NULL",
    "INSERT",
    "INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE",
    "CREATE",
    "TABLE",
    "FUNCTION",
    "REPLACE",
    "RETURNS",
    "LANGUAGE",
    "BEGIN",
    "END",
    "RETURN",
    "DESC",
    "ASC",
    "HAVING",
    "UNION",
    "ALL",
    "DISTINCT",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "LIKE",
    "ILIKE",
    "BETWEEN",
    "EXISTS",
    "WITH",
    "IMMUTABLE",
    "PARALLEL",
    "SAFE",
    "STRICT",
];

/// True when `word` (already uppercased) is a SQL keyword.
pub fn is_keyword(word: &str) -> bool {
    KEYWORDS.contains(&word)
}
